import Bold from './Bold';
import CenterAlign from './CenterAlign';
import Image from './Image';
import Italic from './Italic';
import JustifyAlign from './JustifyAlign';
import LeftAlign from './LeftAlign';
import Link from './Link';
import List from './List';
import ListOrdened from './ListOrdened';
import Redo from './Redo';
import RightAlign from './RightAlign';
import Subtitle from './Subtitle';
import Title from './Title';
import Underline from './Underline';
import Undo from './Undo';
import Unlink from './Unlink';
import Youtube from './Youtube';

export const BoldIcon = Bold;
export const CenterAlignIcon = CenterAlign;
export const ImageIcon = Image;
export const ItalicIcon = Italic;
export const JustifyAlignIcon = JustifyAlign;
export const LeftAlignIcon = LeftAlign;
export const LinkIcon = Link;
export const ListIcon = List;
export const ListOrdenedIcon = ListOrdened;
export const RedoIcon = Redo;
export const RightAlignIcon = RightAlign;
export const SubtitleIcon = Subtitle;
export const TitleIcon = Title;
export const UnderlineIcon = Underline;
export const UndoIcon = Undo;
export const UnlinkIcon = Unlink;
export const YoutubeIcon = Youtube;